name: "Bot action to create automated PRs"
description: "Bot action to create automated PRs"
inputs:
  tfc-token:
    description: "HCP token for authentication"
    required: true
  tfc-organization:
    description: "HCP cloud organization"
    required: true
  tfc-workspace:
    description: "HCP cloud workspace name"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ inputs.tfc_token }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Run Terraform init
      working-directory: feature/github-repo-provisioning
      id: init
      run: terraform init -input=false
      env:
        TF_CLOUD_ORGANIZATION: ${{ inputs.tfc-organization }}
        TF_WORKSPACE: ${{ inputs.tfc-workspace }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Run Terraform plan
      id: plan
      working-directory: feature/github-repo-provisioning
      env:
        TF_CLOUD_ORGANIZATION: ${{ inputs.tfc-organization }}
        TF_WORKSPACE: ${{ inputs.tfc-workspace }}
      run: terraform plan -no-color -input=false -detailed-exitcode
