name: "Terraform Cloud Drift Check"

on:
  workflow_call:
    inputs:
      gcss_ref:
        type: string
        description: "GCSS ref to checkout"
        required: false
        default: "main"

jobs:
  drift-check:
    name: "Drift Check"
    runs-on: ubuntu-latest
    environment: schedule
    steps:
      - name: Checkout GCSS
        uses: actions/checkout@v4
        with:
          repository: gr-oss-developers/github-configuration-self-service
          ref: ${{ inputs.gcss_ref }}
          persist-credentials: false

      - name: Checkout configuration repo
        uses: actions/checkout@v4
        with:
          path: feature/github-repo-provisioning/gcss_config
          ref: ${{ github.sha }}

      - name: Copy importer config
        run: |
          cp feature/github-repo-provisioning/gcss_config/config/app-list.yaml feature/github-repo-importer/app-list.yaml
          cp feature/github-repo-provisioning/gcss_config/config/import-config.yaml feature/github-repo-importer/import-config.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Run Terraform init
        working-directory: feature/github-repo-provisioning
        run: terraform init -input=false
        env:
          TF_CLOUD_ORGANIZATION: "GR-OSS"
          TF_WORKSPACE: ${{ vars.WORKSPACE }}

      - name: Run Terraform plan
        id: plan
        working-directory: feature/github-repo-provisioning
        env:
          TF_CLOUD_ORGANIZATION: "GR-OSS"
          TF_WORKSPACE: ${{ vars.WORKSPACE }}
        run: terraform plan -no-color -input=false -detailed-exitcode

        # 0 for green plan no changes, 2 for green plan with changes
      - name: Inspect drift
        run: |
          if [[ "${{ steps.plan.outputs.exitcode }}" == 2 ]]; then
            echo "Drift detected!"
            exit 1
          else
            echo "No drift detected."
          fi