name: Import repo pipeline

on:
  workflow_call:
    inputs:
      repo_name:
        type: string
        description: 'The name of the repository to import'
        required: true
      owner:
        type: string
        description: 'The owner of the repository to import'
        required: true
      gcss_ref:
        type: string
        description: "GCSS ref to checkout"
        required: false
        default: "main"

jobs:
  import-repo:
    runs-on: ubuntu-latest
    name: Import repository
    environment: import
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: gr-oss-developers/github-configuration-self-service # TODO
          ref: ${{ inputs.gcss_ref }}

      - name: Assemble GCSS
        uses: ./.github/actions/assemble-gcss
        with:
          environment: dev # TODO
          organisation: ${{ inputs.owner }} # TODO

      - name: Setup Just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'

      - name: Generate a token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ inputs.owner }}

      - name: Setup vars
        id: setup-vars
        run: |
          date_suffix=$(date +%Y%m%d)
          echo "full_repo_name=${{ inputs.owner }}/${{ inputs.repo_name }}" >> $GITHUB_OUTPUT
          echo "automation_branch_name=import/dev/${{ inputs.owner }}/${{ inputs.repo_name }}/$date_suffix" >> $GITHUB_OUTPUT # TODO fix hardcoded environment directory 

      - name: Import repo
        working-directory: feature/github-repo-importer
        run: just import-repo ${{ steps.setup-vars.outputs.full_repo_name }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Handle configuration files
        uses: ./.github/actions/compare
        with:
          working-directory: feature/github-repo-importer
          source-directory: "../github-repo-provisioning/importer_tmp_dir/"
          target-directory: "../github-repo-provisioning/repo_configs/dev/${{ inputs.owner }}" # TODO fix hardcoded environment directory

      - name: Create Pull Request
        uses: ./.github/actions/pr-bot
        with:
          branch-name: ${{ steps.setup-vars.outputs.automation_branch_name }}
          pr-title: "Import dev/${{ steps.setup-vars.outputs.full_repo_name }}" # TODO fix hardcoded environment directory
          commit-message: "Auto-generated changes. Import dev/${{ steps.setup-vars.outputs.full_repo_name }} repository" # TODO fix hardcoded environment directory
          github-token: ${{ secrets.GITHUB_TOKEN }}