name: Terraform Plan

on:
  workflow_call:
    inputs:
      commit_sha:
        type: string
        description: 'The commit SHA to promote'
        required: true
      gcss_ref:
        type: string
        description: "GCSS ref to checkout"
        required: false
        default: "main"
    secrets:
      gh_token:
        required: true
      tfc_token:
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: promote
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout GCSS
        uses: actions/checkout@v4
        with:
          repository: gr-oss-developers/github-configuration-self-service
          ref: ${{ inputs.gcss_ref }}
          persist-credentials: false

      - name: Checkout configuration repo
        uses: actions/checkout@v4
        with:
          path: feature/github-repo-provisioning/gcss_config
          ref: ${{ inputs.commit_sha }}
          token: ${{ secrets.gh_token }}
          repository: gr-oss-developers/gr-oss-developers-gcss-config

      - name: Copy GH app mapping
        run: cp feature/github-repo-importer/app-list.yaml feature/github-repo-provisioning/app-list.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.tfc_token }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Run Terraform init
        working-directory: feature/github-repo-provisioning
        id: init
        run: terraform init -input=false
        env:
          TF_CLOUD_ORGANIZATION: "GR-OSS"
          TF_WORKSPACE: ${{ vars.WORKSPACE }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Run Terraform plan
        id: plan
        working-directory: feature/github-repo-provisioning
        env:
          TF_CLOUD_ORGANIZATION: "GR-OSS"
          TF_WORKSPACE: ${{ vars.WORKSPACE }}
        run: terraform plan -no-color -input=false -detailed-exitcode

      - name: Run Terraform apply
        if: steps.plan.outputs.exitcode == '2'
        working-directory: feature/github-repo-provisioning
        env:
          TF_CLOUD_ORGANIZATION: "GR-OSS"
          TF_WORKSPACE: ${{ vars.WORKSPACE }}
        run: terraform apply -no-color -input=false -auto-approve